name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      # We don't fail fast because we want to see version-specific errors
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macOS-12, windows-2022]
        cabal: ["3.10.3.0"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.5"
          - "9.8.2"
          - "9.10.1"
        exclude:
          # fails to build: "can't load framework: Cocoa (not found)"
          - os: macOS-12
            ghc: "8.6.5"
          # fails to build: "can't load framework: Cocoa (not found)"
          - os: macOS-12
            ghc: "8.8.4"

    steps:
    - uses: actions/checkout@v4
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Enable -Werror
      shell: bash
      run: |
        [ -e cabal.project ] && exit 1
        echo -e 'packages: *.cabal\npackage hakyll\n  ghc-options: -Werror' > cabal.project

    - name: Freeze
      run: |
        cabal update
        cabal freeze
        # Exclude the timestamp of Hackage index update from our cache key, to
        # avoid invalidating cache too often.
        sed '/^index-state: /d' cabal.project.freeze > dependencies-versions

    - uses: actions/cache@v4
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('dependencies-versions') }}

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cabal test all

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stack: ["2.15.7"]
        ghc: ["9.6.5"] # We want this to match the Stackage snapshot in stack.yaml

    steps:
    - uses: actions/checkout@v4
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v4
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --pedantic

    - name: Test
      run: |
        stack test --system-ghc

  sdist:
    name: Cabal file is up-to-date
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc: ["9.2.8"]

    steps:
    - uses: actions/checkout@v4
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze
      run: |
        cabal freeze
        # Exclude the timestamp of Hackage index update from our cache key, to
        # avoid invalidating cache too often.
        sed '/^index-state: /d' cabal.project.freeze > dependencies-versions

    - uses: actions/cache@v4
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('dependencies-versions') }}

    - name: Prepare Cabal package
      run: |
        cabal sdist

    - name: Unpack Cabal package
      run: |
        cd dist-newstyle/sdist
        tar xvf ./*.tar.gz
        rm -f ./*.tar.gz

    - name: Build
      run: |
        cd dist-newstyle/sdist/hakyll-*
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cd dist-newstyle/sdist/hakyll-*
        cabal test all
